# KITTI monocular model for seq.04-12

#System:
#  num_grid_cols: 40
#  num_grid_rows: 13

#==============#
# Camera Model #
#==============#

Camera:
  name: "flir"
  setup: "monocular"
  model: "perspective"

  fx: 808.53532
  fy: 808.69014
  cx: 954.58424
  cy: 738.02845

  k1: -5.300319e-03
  k2: -4.247141e-03
  p1: -9.770585e-04
  p2: -2.668703e-04
  k3: 2.444739e-03

  fps: 60.0
  cols: 1936
  rows: 1464

  color_order: "BGR"

#=====================#
# Tracking Parameters #
#=====================#

Preprocessing:
  min_size: 800

#================#
# ORB Parameters #
#================#

Feature:
  name: "ORB"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20 #20
  min_fast_threshold: 7 #7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 0.06
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.07
  camera_line_width: 2
  viewpoint_x: 0
  viewpoint_y: -20
  viewpoint_z: -0.1
  viewpoint_f: 2800
