# KITTI monocular model for seq.04-12

#System:
#  num_grid_cols: 40
#  num_grid_rows: 13

#==============#
# Camera Model #
#==============#

Camera:
  name: "flir"
  setup: "monocular"
  model: "perspective"

  fx: 1842.19838
  fy: 1842.24282
  cx: 977.99329
  cy: 718.38872

  k1: -0.09292354
  k2: 0.1737044
  p1: 0.00009261826
  p2: 0.0008889984
  k3: 0.03704454

  fps: 60.0
  cols: 1936
  rows: 1464

  color_order: "BGR"

#=====================#
# Tracking Parameters #
#=====================#

Preprocessing:
  min_size: 800

#================#
# ORB Parameters #
#================#

Feature:
  name: "ORB"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

#====================#
# Mapping Parameters #
#====================#

Mapping:
  baseline_dist_thr_ratio: 0.02
  redundant_obs_ratio_thr: 0.9
  num_covisibilities_for_landmark_generation: 20
  num_covisibilities_for_landmark_fusion: 20

#===========================#
# PangolinViewer Parameters #
#===========================#

PangolinViewer:
  keyframe_size: 0.06
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.07
  camera_line_width: 2
  viewpoint_x: 0
  viewpoint_y: -20
  viewpoint_z: -0.1
  viewpoint_f: 2800
